version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: database_foo
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./test_db_mysql/:/var/test_db/
    ports:
      - "3306:3306"
      
volumes:
  mysql_data:
    driver: local

networks:
  default:
    driver: bridge